version: '3.3'
services:
    mongo-1:
        hostname: mongo-1
        image: mongo:3.5.13
        deploy:
          replicas: 1
        entrypoint:
          - mongod
          - --replSet
          - rs1
          - --bind_ip
          - 0.0.0.0
        ports:
            - "30011:27017"
        networks:
          - "mongo"
    mongo-2:
        hostname: mongo-2
        image: mongo:3.5.13
        deploy:
          replicas: 1
        entrypoint:
          - mongod
          - --replSet
          - rs1
          - --bind_ip
          - 0.0.0.0
        ports:
            - "30012:27017"
        networks:
          - "mongo"
    mongo-arb:
        hostname: mongo-arb
        image: mongo:3.5.13
        deploy:
          replicas: 1
        entrypoint:
          - mongod
          - --replSet
          - rs1
          - --bind_ip
          - 0.0.0.0
        networks:
          - "mongo"
          
    configure-replicaset:
        image: mongo:3.5.13
        deploy:
          replicas: 1
        volumes:
          - ./scripts:/scripts
        environment: 
          - MONGO1=mongo-1
          - MONGO2=mongo-2
          - MONGOARB=mongo-arb
          - RS=rs1
        entrypoint: [ "bash", "/scripts/setup.sh" ]    
        networks:
          - "mongo"
        
networks:
    mongo:
        driver: overlay
        attachable: true